# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e362ff409535b355e4ccec7c1e3f224d3e8e28ed7e45bdc030f56815f5ac5aa55726c62350820a2028f9c6a5afabc19e0e43eb6a6c23a7db94d17a7acc4c425

test:
  secret_key_base: 900671a3d9649575d035d8fcbdc5c62d9d2184b05e95b13d0652d875aa50df47d4086c6cf77e9d6987445707fcd04346ca6b63fd3f0107e842b33f390cd81b38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
